name: reteno_plugin_example
description: Demonstrates how to use the reteno_plugin plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+120
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  app_links: ^3.4.3
  cupertino_icons: ^1.0.2
  # firebase_core: ^2.14.0
  # firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.1.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  go_router: ^7.1.1
  reteno_plugin: 
    path: ../
  sentry_flutter: ^7.6.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
