name: reteno_plugin_example
description: Demonstrates how to use the reteno_plugin plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+292
environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  app_links: ^3.4.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_local_notifications: ^18.0.1
  flutter_foreground_task: ^6.1.3
  form_builder_validators: ^8.4.0
  go_router: ^7.1.1
  permission_handler: ^11.0.1
  reteno_plugin:
    path: ../
  shared_preferences: ^2.2.2
  uuid: ^3.0.7

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
